import { useEffect, useRef } from "react";
import { Bot, Zap, BarChart2, TrendingUp, ShieldCheck, Star } from "lucide-react";
import { GlitchText, SpotlightCard } from "./Effects";

/**
 * The instruments rail — a sideways journey. The section pins while you
 * scroll and the six instruments slide horizontally through the viewport,
 * each numbered like a track listing. Vertical scroll IS the horizontal
 * position (scrubbing back rewinds), with a heat→signal progress hairline
 * under the rail.
 *
 * Desktop-only (lg+); the caller renders the stacked grid on smaller
 * screens where pinned horizontal scroll fights native touch scrolling.
 */

export const INSTRUMENTS = [
  { icon: Bot,         title: "AI Stock Analysis",       desc: "Claude AI analyzes every stock with live data injected — grounded in real numbers, not generic advice." },
  { icon: Zap,         title: "Natural Language Search", desc: "Ask 'profitable tech stocks under PE 25' and get a filtered list back in seconds." },
  { icon: BarChart2,   title: "Volume Profile Chart",    desc: "Real historical volume by price level — identifies support and resistance, not fake order book data." },
  { icon: TrendingUp,  title: "Portfolio P&L",           desc: "Track your real gains with auto-lookup of historical buy prices and AI sell signals." },
  { icon: ShieldCheck, title: "Custom Criteria",         desc: "Define your own buy/watch/sell rules visually. Changes apply to your screener immediately." },
  { icon: Star,        title: "90-Day Prediction",       desc: "Bull/base/bear price projections generated by Claude from recent momentum and fundamentals." },
];

export default function InstrumentsRail() {
  const sectionRef = useRef<HTMLElement>(null);
  const trackRef = useRef<HTMLDivElement>(null);
  const barRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) return;
    const section = sectionRef.current;
    const track = trackRef.current;
    if (!section || !track) return;

    let rafId = 0;
    let ticking = false;

    function apply() {
      ticking = false;
      const r = section!.getBoundingClientRect();
      const vh = window.innerHeight;
      // Progress through the pinned span: 0 while the section top is at the
      // viewport top, 1 when its bottom reaches the viewport bottom.
      const span = r.height - vh;
      const p = span > 0 ? Math.max(0, Math.min(1, -r.top / span)) : 0;
      // The track is w-max (its clientWidth IS its content width), so the
      // traversable distance is measured against the viewport that clips it
      const overflow = Math.max(0, track!.scrollWidth - window.innerWidth);
      track!.style.transform = `translateX(${-p * overflow}px)`;
      if (barRef.current) barRef.current.style.transform = `scaleX(${p})`;
    }

    function onScroll() {
      if (!ticking) { ticking = true; rafId = requestAnimationFrame(apply); }
    }

    window.addEventListener("scroll", onScroll, { passive: true });
    window.addEventListener("resize", onScroll, { passive: true });
    apply();
    return () => {
      window.removeEventListener("scroll", onScroll);
      window.removeEventListener("resize", onScroll);
      cancelAnimationFrame(rafId);
    };
  }, []);

  return (
    <section ref={sectionRef} className="relative z-10" style={{ height: "280vh" }}>
      <div className="sticky top-0 h-screen flex flex-col justify-center overflow-hidden">

        <div className="px-8 mb-10 max-w-7xl mx-auto w-full">
          <p className="font-mono text-[11px] tracking-[0.28em] text-purple uppercase mb-3"><GlitchText text="Instruments" /></p>
          <h2 className="font-display font-bold tracking-tight text-4xl md:text-5xl text-white">
            Six instruments, <span className="text-gradient-heat">one terminal.</span>
          </h2>
        </div>

        {/* The rail — scroll scrubs it sideways */}
        <div ref={trackRef} className="flex gap-5 px-8 will-change-transform w-max">
          {INSTRUMENTS.map(({ icon: Icon, title, desc }, i) => {
            const heat = i % 2 === 0;
            const accent = heat ? "#FF5C7A" : "#8055F5";
            const spotColor = heat ? "rgba(255,61,92,0.12)" : "rgba(124,92,255,0.14)";
            return (
              <SpotlightCard key={title} color={spotColor}
                className="glass-card border border-white/[0.07] rounded-3xl p-7 w-[380px] flex-shrink-0 flex flex-col justify-between min-h-[300px]">
                {/* Track number — giant, outlined, the rail's own type moment */}
                <span aria-hidden className="font-display font-black text-[84px] leading-none block select-none"
                  style={{ WebkitTextStroke: `1.5px ${accent}66`, color: "transparent" }}>
                  {String(i + 1).padStart(2, "0")}
                </span>
                <div>
                  <div className="w-10 h-10 rounded-xl border flex items-center justify-center mb-4"
                    style={{ color: accent, borderColor: `${accent}33`, background: `${accent}1A` }}>
                    <Icon size={18} />
                  </div>
                  <p className="font-mono text-sm tracking-[0.12em] uppercase text-white mb-2">{title}</p>
                  <p className="text-muted text-sm leading-relaxed">{desc}</p>
                </div>
              </SpotlightCard>
            );
          })}
          {/* Terminal card — the rail resolves into the CTA */}
          <div className="rounded-3xl p-7 w-[300px] flex-shrink-0 flex flex-col items-start justify-center border"
            style={{ background: "linear-gradient(135deg, rgba(255,61,92,0.1), rgba(124,92,255,0.1))", borderColor: "rgba(255,61,92,0.25)" }}>
            <p className="font-display font-bold text-2xl text-white leading-snug mb-3">
              All of it, in one dark terminal.
            </p>
            <p className="font-mono text-[11px] tracking-[0.2em] uppercase text-red">Scroll on ↓</p>
          </div>
        </div>

        {/* Progress hairline */}
        <div className="px-8 mt-10 max-w-7xl mx-auto w-full">
          <div className="h-px bg-white/10 overflow-hidden rounded">
            <div ref={barRef} className="h-full origin-left"
              style={{ transform: "scaleX(0)", background: "linear-gradient(90deg, #FF3D5C, #FF7A3D 45%, #7C5CFF)" }} />
          </div>
        </div>
      </div>
    </section>
  );
}
